# Generated by Django 2.2.6 on 2019-10-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20191020_0832'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
    ]
