# Generated by Django 2.2.6 on 2019-10-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20191020_0841'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='projects',
            table=None,
        ),
    ]
